# Generated by Django 2.1.4 on 2018-12-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('nombreB', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('direccionB', models.CharField(max_length=225)),
                ('telefonoB', models.CharField(max_length=10)),
                ('correoB', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('genero', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=15)),
                ('estadoCivil', models.CharField(max_length=15)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estadoC', models.BooleanField(default=True)),
                ('fechaApertura', models.DateField(auto_now_add=True)),
                ('saldo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tipoCuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorro'), ('basica', 'Básica'), ('nomina', 'Nómina'), ('valores', 'Valores'), ('juvenil', 'Juvenil'), ('programado', 'Ahorro Programado'), ('euros', 'Ahorro en Euros')], max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('transaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia'), ('prestamo', 'Pago de Prestamo'), ('nomina', 'Pagos de Nómina'), ('pensiones', 'Pagos de Pensiones'), ('dividendos', 'Dividendos'), ('reembolsoGastos', 'Reembolso de Gastos'), ('pagoProveedores', 'Reembolso de Gastos'), ('transferencia', 'Traslado de efectivo entre entidades bancarias'), ('seguros', 'Pago de Seguros'), ('iess', 'Pago del IESS'), ('hipotecas', 'Pago de Hipotecas'), ('serviciosBasico', 'Pago de Servicios Básicos'), ('tvCable', 'Cuentas de televisión por cable'), ('celular', 'Cuentas de celular'), ('online', 'Compras por Internet'), ('administracion', 'Servicio de Administración'), ('futuros', 'Pagos Futuros')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(max_length=160)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Cuenta')),
            ],
        ),
    ]
