# Generated by Django 2.1.4 on 2018-12-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('s', 'Soltero'), ('c', 'Casado'), ('v', 'Viudo'), ('d', 'Divorciado')], max_length=15),
        ),
    ]
