# Generated by Django 2.1.4 on 2018-12-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_auto_20181228_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
