# Generated by Django 2.1.4 on 2018-12-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_auto_20181228_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=7),
        ),
    ]
